### ISSUE TITLE
Unable to test HTML game using editor

### ISSUE THREAD

**Issue by JamesTDG** [circlejourney/theditor#6]
Game in question: https://2dwillneverdie.com/blog/add-an-interactive-game-character-to-your-web-page/#savepoint
Code: https://2dwillneverdie.com/DLC/fullzeldacode.txt
So, I am trying to make a really interactive toyhouse profile, but I am unable to test the code to see if it would even look right on toyhouse. 

I've had no luck getting it to run even the first blurb of the HTML correctly, the furthest I was getting was pasting the code in both the HTML and CSS boxes and while I do see the game, it is not accepting user inputs.

**Comment by JamesTDG** [comment]
Update: Toyhouse will never let me have this game run anyways due to cloudflare banning the <script> tag, even if you use it in the WYSIWYG text editor, which is odd...

**Comment by circlejourney** [comment]
So, I did actually block the script tag in the editor just to prevent code injection that messes up the display in a way that soft-locks the editor (e.g. a script that crashes the browser the moment it loads - this has happened before) and because it imitates the behaviour of code on Toyhouse more accurately (as you noted, TH doesn't allow script embeds)

Allowing scripting is outside the scope of this project at the moment - if you want something that can run JS, try http://htmledit.squarefree.com/ or JSFiddle!
